### ISSUE TITLE
Failing to authenticate with trakt.tv

### ISSUE THREAD

**Issue by Lockszmith** [SimonVT/cathode#11]
Just downloaded the software from the play store.
clicked the Sign in button
logged into trakt.tv
clicked authorize in the trakt.tv website. 
Returning back to cathode it says:
Traktor has encountered a server error, please try again later.

**Comment by Lockszmith** [comment]
I'm looking where to post this on trakt.tv too

**Comment by Lockszmith** [comment]
I feel so immature and without patient. Testing again 15 minutes later.  The Auth went through.
a trakt.tv issue all the way. 

Sorry. 
Closing issue.

**Comment by SimonVT** [comment]
If Cathode explicitly says Trakt has encountered a server error, then the issue is on their end. Nothing to do but try again.
