### ISSUE TITLE
Filter episode calendar by TV show

### ISSUE THREAD

**Issue by loket** [SimonVT/cathode#12]
It would be nice to be able to filter the episode calendar by TV shows, or to disable it altogether. I'm not really interested in knowing when any of my shows are aired, and there is currently no way of disabling this feature, so it generates a lot of unwanted clutter in my calendar.

Alternatively, make the episodes appear in a separate calendar, so I can disable that calendar in my normal calendar app.

**Comment by SimonVT** [comment]
Trakt has a calendar you can hide shows from. Once they add APIs for the list of hidden shows, I'll add the same feature to Cathode.

The episodes already appear in a separate calendar called "Upcoming episodes". You can disable that from your calendar app.
