### ISSUE TITLE
Option for choosing startpage

### ISSUE THREAD

**Issue by DJaeger** [SimonVT/cathode#13]
It would be great, if it would be possible to choose the page/list that will be shown on starting the app.
As I do not watch any shows, I do not want to see my empty upcoming shows list every time I start the app.
I would like to see the Movie-Watchlist.

**Comment by renatoagds** [comment]
Good idea. :+1:

I will start working in this feature.

**Comment by DJaeger** [comment]
@renatoagds: Any news on this?

**Comment by DJaeger** [comment]
@renatoagds: Any news on this?

**Comment by SimonVT** [comment]
Added and released :)

**Comment by DJaeger** [comment]
Thanks
