### ISSUE TITLE
API key in options

### ISSUE THREAD

**Issue by DJaeger** [SimonVT/cathode#15]
Add a link to get an own API key (mayby automaticly get a key if possible by API) and an option to set an own API key to use by app in settings.

**Comment by DJaeger** [comment]
If API key is predefined on building this option could be hidden so that a build with predefined API key for example for google play store is still possible.

**Comment by DJaeger** [comment]
I think for this the API key have to be deployed to gladle build as gradle build parameter, without python script.

**Comment by SimonVT** [comment]
A default api key has been added to the project, debug builds should work out of the box now.
