### ISSUE TITLE
Need Feature to Hide Shows

### ISSUE THREAD

**Issue by JakeWharton** [SimonVT/cathode#2]
People give up on shows. My list is littered with a few shows that I've completely abandoned because they were crap from episode 1 or jumped the shark later on.

**Comment by simba83** [comment]
Any news on this, would be nice to remove/hide tv shows who shows on the upcoming shows, aired page.
If the trakt api doesn't support it is it possible to put the feature only in the app?

**Comment by SimonVT** [comment]
Still no API support. I'm against adding features with state that can't be synced with trakt, but I think it's about time I add this..

**Comment by simba83** [comment]
I saw that I could remove them using hide button on the trakt.tv page, but I have to find the series calender date and from calender mode hide it. Is it possible to use that function in some kind of way otherwise.

**Comment by SimonVT** [comment]
Yeah, shows and movies hidden on the trakt website can be synced to the app - not the other way around.
