### ISSUE TITLE
Hidden titles in "Upcoming" started appearing

### ISSUE THREAD

**Issue by mionejgp** [SimonVT/cathode#24]
Since the weekend, the shows I have hidden in the upcoming (hidden in the trakt website) started appearing on the app. Did something change?

Thank you!

**Comment by SimonVT** [comment]
Yep, sorry, please hide them again :)
Hidden items are now synced with trakt (e.g. hiding from upcoming hides it from the calendar on trakt.tv), but I forgot to sync your already hidden items.
