### ISSUE TITLE
Watchlist serie removed after checked an episode

### ISSUE THREAD

**Issue by andreagualandi** [SimonVT/cathode#27]
As the title said, if i've a TV series in my watchlist and i check an episode of that serie as viewed...the entire serie is removed from the watchlist and marked as  watched

**Comment by SimonVT** [comment]
Indeed, Trakt removes items from the watchlist once you've started watching them: http://support.trakt.tv/knowledgebase/articles/154739-why-do-things-get-removed-from-my-watchlist-after

As long as shows have unwatched episodes you can find them on the "Upcoming" screen.
