### ISSUE TITLE
Deleted episode still listed in Cathode

### ISSUE THREAD

**Issue by antonsoroko** [SimonVT/cathode#32]
Hi.
Please see the screenshot.
Even if I mark it as watched it appears again.
Link refers to https://trakt.tv/search/trakt/3201832?id_type=episode
Thank you.

![screenshot_20181107-152920](https://user-images.githubusercontent.com/17964763/48131861-8e03e780-e2a2-11e8-93f5-5ec862339fdc.png)

![screenshot_20181107-153024](https://user-images.githubusercontent.com/17964763/48131855-89d7ca00-e2a2-11e8-9794-1f59fb8e096e.png)

**Comment by antonsoroko** [comment]
Looks like the problem is in (some kind of) caching at the app side.
Also it would be nice to have auto-update/auto-sync with Trak. Or if it exists - possibility to tune it and force it.

**Comment by bytet** [comment]
Maybe the local cache should be cleared on the device. It seems like on my
TV device some apps work better after the cache is cleared.

**Comment by SimonVT** [comment]
Fixed syncing in latest version.

**Comment by antonsoroko** [comment]
Thank you very much!
