### ISSUE TITLE
Sorting Option in Custom List

### ISSUE THREAD

**Issue by hfhennbdhxhsj** [SimonVT/cathode#34]
Sorting By date added, name.

**Comment by bytet** [comment]
Latest update seemed to break the widget which is my primary interest. It was stuck on loading calendar. Reinstalling a version I saved from last summer fixed my issue. Still the coolest widget I have to connect to trakt. Thank you for all your hard work.

**Comment by SimonVT** [comment]
Implemented in version 7.
