### ISSUE TITLE
Automatically remove leading and trailing whitespaces when do search

### ISSUE THREAD

**Issue by antonsoroko** [SimonVT/cathode#37]
Now if you copy something and paste to cathode and if this something has leading or trailing whitespaces - no search result. If you remove all these whitespaces manually - search works.

**Comment by SimonVT** [comment]
Fixed in latest release.

**Comment by antonsoroko** [comment]
@SimonVT 
It works, thanks!
I guess i found a new bug - if you don't click search button and wait for results - then search works. If you click search button - search get stuck in "searching...".

**Comment by SimonVT** [comment]
Nice catch, will fix :)
